language: java
sudo: false

matrix:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
    - os: linux
      dist: trusty
      jdk: openjdk7
    - os: osx
      osx_image: xcode8.3

before_install:
  - nvm install node
  - npm install

script:
  - npm test
  - npm run lint-js

cache:
  directories:
    - $HOME/.m2
    - $HOME/.npm
